[package]
name = "scanner_cargo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4"
json = "0.12.4"
serde = "1.0.201"
serde_json = "1.0.117"
similar-string = "1.4.3"
value = "0.1.1"
